<a href="https://colab.research.google.com/github/sabaakram539/data_analysis_projects/blob/main/1_Weather_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Weather Data
Here the weather dataset is a time series dataset with per hour information about the weather conditions at a particular location. It records temperature, Dew Point Temperature, Relative Humidity, windspeed, visibility pressure and conditions.

The data is available as a csv file. We are going to analyse this data using the pandas dataframe.

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv('1. Weather Data.csv')
data.head()

       Date/Time  Temp_C  ...  Press_kPa               Weather
0  1/1/2012 0:00    -1.8  ...     101.24                   Fog
1  1/1/2012 1:00    -1.8  ...     101.24                   Fog
2  1/1/2012 2:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3  1/1/2012 3:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4  1/1/2012 4:00    -1.5  ...     101.23                   Fog

[5 rows x 8 columns]

In [ ]:
data.shape

(8784, 8)

In [ ]:
data.index

RangeIndex(start=0, stop=8784, step=1)

In [ ]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [ ]:
data.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [ ]:
data.rename(columns={'Date/Time':'Date_Time','Temp_C':'Temperature','Dew Point Temp_C':'Dew_Pt_Temp',
                     'Rel Hum_%':'Relative_Humidity','Wind Speed_km/h':'Wind_Speed','Visibility_km':'Visibility'
                     ,'Press_kPa':'Pressure'},inplace=True)

In [ ]:
data.columns

Index(['Date_Time', 'Temperature', 'Dew_Pt_Temp', 'Relative_Humidity',
       'Wind_Speed', 'Visibility', 'Pressure', 'Weather'],
      dtype='object')

In [ ]:
 data.Weather.unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [ ]:
 data.Weather.nunique()

50

In [ ]:
data.Weather.value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Snow Showers,Fog                              4
Freezing Fog                                  4
Moderate Snow                                 4
Freezing Rain,Fog                             4
Rain,Snow,Ice Pellets                         4
Rain,Haze                                     3
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Rain Showers,Snow Showers                     2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Thunderstorms,Moderate Rain Showers,Fog       1
Freezing Rain,Snow Grains                     1
Rain,Ice Pellets                              1
Drizzle,Ice Pellets,Fog                       1
Rain Showers,Fog                              1
Rain,Snow Grains                              1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Rain,Snow,Fog                                 1
Thunderstorms,Rain,Fog                        1
Snow Pellets                                  1
Thunderstorms,Heavy Rain Showers              1
Name: Weather, dtype: int64

In [ ]:
data.count()

Date_Time            8784
Temperature          8784
Dew_Pt_Temp          8784
Relative_Humidity    8784
Wind_Speed           8784
Visibility           8784
Pressure             8784
Weather              8784
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date_Time          8784 non-null   object
 1   Temperature        8784 non-null   float64
 2   Dew_Pt_Temp        8784 non-null   float64
 3   Relative_Humidity  8784 non-null   int64
 4   Wind_Speed         8784 non-null   int64
 5   Visibility         8784 non-null   float64
 6   Pressure           8784 non-null   float64
 7   Weather            8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [ ]:
data.describe()

       Temperature  Dew_Pt_Temp  ...   Visibility     Pressure
count  8784.000000  8784.000000  ...  8784.000000  8784.000000
mean      8.798144     2.555294  ...    27.664447   101.051623
std      11.687883    10.883072  ...    12.622688     0.844005
min     -23.300000   -28.500000  ...     0.200000    97.520000
25%       0.100000    -5.900000  ...    24.100000   100.560000
50%       9.300000     3.300000  ...    25.000000   101.070000
75%      18.800000    11.800000  ...    25.000000   101.590000
max      33.000000    24.400000  ...    48.300000   103.650000

[8 rows x 6 columns]

In [ ]:
data.Weather.unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [ ]:
data.Weather.nunique()

50

In [ ]:
data.Weather.value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Snow Showers,Fog                              4
Freezing Fog                                  4
Moderate Snow                                 4
Freezing Rain,Fog                             4
Rain,Snow,Ice Pellets                         4
Rain,Haze                                     3
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Rain Showers,Snow Showers                     2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Thunderstorms,Moderate Rain Showers,Fog       1
Freezing Rain,Snow Grains                     1
Rain,Ice Pellets                              1
Drizzle,Ice Pellets,Fog                       1
Rain Showers,Fog                              1
Rain,Snow Grains                              1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Rain,Snow,Fog                                 1
Thunderstorms,Rain,Fog                        1
Snow Pellets                                  1
Thunderstorms,Heavy Rain Showers              1
Name: Weather, dtype: int64

Finding all unique windspeed values

In [ ]:
data.head(2)

       Date_Time  Temperature  Dew_Pt_Temp  ...  Visibility  Pressure  Weather
0  1/1/2012 0:00         -1.8         -3.9  ...         8.0    101.24      Fog
1  1/1/2012 1:00         -1.8         -3.7  ...         8.0    101.24      Fog

[2 rows x 8 columns]

In [ ]:
data.Wind_Speed.unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

In [ ]:
data.Wind_Speed.nunique()

34

Finding number of times weather is exactly clear.

In [ ]:
# Value_Counts
data.Weather.value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Snow Showers,Fog                              4
Freezing Fog                                  4
Moderate Snow                                 4
Freezing Rain,Fog                             4
Rain,Snow,Ice Pellets                         4
Rain,Haze                                     3
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Rain Showers,Snow Showers                     2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Thunderstorms,Moderate Rain Showers,Fog       1
Freezing Rain,Snow Grains                     1
Rain,Ice Pellets                              1
Drizzle,Ice Pellets,Fog                       1
Rain Showers,Fog                              1
Rain,Snow Grains                              1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Rain,Snow,Fog                                 1
Thunderstorms,Rain,Fog                        1
Snow Pellets                                  1
Thunderstorms,Heavy Rain Showers              1
Name: Weather, dtype: int64

In [ ]:
#Filtering
data[data.Weather=='Clear']

             Date_Time  Temperature  Dew_Pt_Temp  ...  Visibility  Pressure  Weather
67      1/3/2012 19:00        -16.9        -24.8  ...        25.0    101.74    Clear
114     1/5/2012 18:00         -7.1        -14.4  ...        25.0    100.71    Clear
115     1/5/2012 19:00         -9.2        -15.4  ...        25.0    100.80    Clear
116     1/5/2012 20:00         -9.8        -15.7  ...        25.0    100.83    Clear
117     1/5/2012 21:00         -9.0        -14.8  ...        25.0    100.83    Clear
...                ...          ...          ...  ...         ...       ...      ...
8646   12/26/2012 6:00        -13.4        -14.8  ...        25.0    102.47    Clear
8698  12/28/2012 10:00         -6.1         -8.6  ...        24.1    101.27    Clear
8713   12/29/2012 1:00        -11.9        -13.6  ...        25.0    101.31    Clear
8714   12/29/2012 2:00        -11.8        -13.1  ...        25.0    101.33    Clear
8756  12/30/2012 20:00        -13.8        -16.5  ...        25.0    101.52    Clear

[1326 rows x 8 columns]

In [ ]:
#Groupby Method
data.groupby('Weather').get_group('Clear')

             Date_Time  Temperature  Dew_Pt_Temp  ...  Visibility  Pressure  Weather
67      1/3/2012 19:00        -16.9        -24.8  ...        25.0    101.74    Clear
114     1/5/2012 18:00         -7.1        -14.4  ...        25.0    100.71    Clear
115     1/5/2012 19:00         -9.2        -15.4  ...        25.0    100.80    Clear
116     1/5/2012 20:00         -9.8        -15.7  ...        25.0    100.83    Clear
117     1/5/2012 21:00         -9.0        -14.8  ...        25.0    100.83    Clear
...                ...          ...          ...  ...         ...       ...      ...
8646   12/26/2012 6:00        -13.4        -14.8  ...        25.0    102.47    Clear
8698  12/28/2012 10:00         -6.1         -8.6  ...        24.1    101.27    Clear
8713   12/29/2012 1:00        -11.9        -13.6  ...        25.0    101.31    Clear
8714   12/29/2012 2:00        -11.8        -13.1  ...        25.0    101.33    Clear
8756  12/30/2012 20:00        -13.8        -16.5  ...        25.0    101.52    Clear

[1326 rows x 8 columns]

Finding number of times when the windspeed is exactly 4 km/h

In [ ]:
data.head(2)

       Date_Time  Temperature  Dew_Pt_Temp  ...  Visibility  Pressure  Weather
0  1/1/2012 0:00         -1.8         -3.9  ...         8.0    101.24      Fog
1  1/1/2012 1:00         -1.8         -3.7  ...         8.0    101.24      Fog

[2 rows x 8 columns]

In [ ]:
#Filtering
data[data.Wind_Speed==4]

             Date_Time  Temperature  ...  Pressure       Weather
0        1/1/2012 0:00         -1.8  ...    101.24           Fog
1        1/1/2012 1:00         -1.8  ...    101.24           Fog
96       1/5/2012 0:00         -8.8  ...    100.32          Snow
101      1/5/2012 5:00         -7.0  ...    100.19          Snow
146      1/7/2012 2:00         -8.1  ...    100.15        Cloudy
...                ...          ...  ...       ...           ...
8768   12/31/2012 8:00         -8.6  ...    101.14  Snow Showers
8769   12/31/2012 9:00         -8.1  ...    101.09          Snow
8770  12/31/2012 10:00         -7.4  ...    101.05      Snow,Fog
8772  12/31/2012 12:00         -5.8  ...    100.78          Snow
8773  12/31/2012 13:00         -4.6  ...    100.63          Snow

[474 rows x 8 columns]

In [ ]:
# Value Counts method
data.Wind_Speed.value_counts()

9     830
11    791
13    735
15    719
7     677
17    666
19    616
6     609
20    496
4     474
22    439
24    374
0     309
26    242
28    205
30    161
32    139
33     85
35     53
37     45
39     24
41     22
44     14
43     13
48     13
46     11
52      7
57      5
50      4
2       2
63      1
54      1
70      1
83      1
Name: Wind_Speed, dtype: int64

In [ ]:
# Groupby Method
data.groupby('Wind_Speed').get_group(4)

             Date_Time  Temperature  ...  Pressure       Weather
0        1/1/2012 0:00         -1.8  ...    101.24           Fog
1        1/1/2012 1:00         -1.8  ...    101.24           Fog
96       1/5/2012 0:00         -8.8  ...    100.32          Snow
101      1/5/2012 5:00         -7.0  ...    100.19          Snow
146      1/7/2012 2:00         -8.1  ...    100.15        Cloudy
...                ...          ...  ...       ...           ...
8768   12/31/2012 8:00         -8.6  ...    101.14  Snow Showers
8769   12/31/2012 9:00         -8.1  ...    101.09          Snow
8770  12/31/2012 10:00         -7.4  ...    101.05      Snow,Fog
8772  12/31/2012 12:00         -5.8  ...    100.78          Snow
8773  12/31/2012 13:00         -4.6  ...    100.63          Snow

[474 rows x 8 columns]

Finding null values

In [ ]:
data.isnull().sum()

Date_Time            0
Temperature          0
Dew_Pt_Temp          0
Relative_Humidity    0
Wind_Speed           0
Visibility           0
Pressure             0
Weather              0
dtype: int64

In [ ]:
data.notnull().sum()

Date_Time            8784
Temperature          8784
Dew_Pt_Temp          8784
Relative_Humidity    8784
Wind_Speed           8784
Visibility           8784
Pressure             8784
Weather              8784
dtype: int64

Finding instances when the snow is recorded.

In [ ]:
# Value Counts
data.Weather.value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Snow Showers,Fog                              4
Freezing Fog                                  4
Moderate Snow                                 4
Freezing Rain,Fog                             4
Rain,Snow,Ice Pellets                         4
Rain,Haze                                     3
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Rain Showers,Snow Showers                     2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Thunderstorms,Moderate Rain Showers,Fog       1
Freezing Rain,Snow Grains                     1
Rain,Ice Pellets                              1
Drizzle,Ice Pellets,Fog                       1
Rain Showers,Fog                              1
Rain,Snow Grains                              1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Rain,Snow,Fog                                 1
Thunderstorms,Rain,Fog                        1
Snow Pellets                                  1
Thunderstorms,Heavy Rain Showers              1
Name: Weather, dtype: int64

In [ ]:
#filtering
data[data.Weather=='Snow']

             Date_Time  Temperature  Dew_Pt_Temp  ...  Visibility  Pressure  Weather
55       1/3/2012 7:00        -14.0        -19.5  ...        25.0    100.95     Snow
84      1/4/2012 12:00        -13.7        -21.7  ...        24.1    101.25     Snow
86      1/4/2012 14:00        -11.3        -19.0  ...        19.3    100.97     Snow
87      1/4/2012 15:00        -10.2        -16.3  ...         9.7    100.89     Snow
88      1/4/2012 16:00         -9.4        -15.5  ...        19.3    100.79     Snow
...                ...          ...          ...  ...         ...       ...      ...
8779  12/31/2012 19:00          0.1         -2.7  ...         9.7    100.13     Snow
8780  12/31/2012 20:00          0.2         -2.4  ...         9.7    100.03     Snow
8781  12/31/2012 21:00         -0.5         -1.5  ...         4.8     99.95     Snow
8782  12/31/2012 22:00         -0.2         -1.8  ...         9.7     99.91     Snow
8783  12/31/2012 23:00          0.0         -2.1  ...        11.3     99.89     Snow

[390 rows x 8 columns]

In [ ]:
#Groupby method
data.groupby('Weather').get_group('Snow')

             Date_Time  Temperature  Dew_Pt_Temp  ...  Visibility  Pressure  Weather
55       1/3/2012 7:00        -14.0        -19.5  ...        25.0    100.95     Snow
84      1/4/2012 12:00        -13.7        -21.7  ...        24.1    101.25     Snow
86      1/4/2012 14:00        -11.3        -19.0  ...        19.3    100.97     Snow
87      1/4/2012 15:00        -10.2        -16.3  ...         9.7    100.89     Snow
88      1/4/2012 16:00         -9.4        -15.5  ...        19.3    100.79     Snow
...                ...          ...          ...  ...         ...       ...      ...
8779  12/31/2012 19:00          0.1         -2.7  ...         9.7    100.13     Snow
8780  12/31/2012 20:00          0.2         -2.4  ...         9.7    100.03     Snow
8781  12/31/2012 21:00         -0.5         -1.5  ...         4.8     99.95     Snow
8782  12/31/2012 22:00         -0.2         -1.8  ...         9.7     99.91     Snow
8783  12/31/2012 23:00          0.0         -2.1  ...        11.3     99.89     Snow

[390 rows x 8 columns]

In [ ]:
#Str.contains method
data[data.Weather.str.contains('Snow')]

             Date_Time  Temperature  ...  Pressure       Weather
41      1/2/2012 17:00         -2.1  ...     99.66  Snow Showers
44      1/2/2012 20:00         -5.6  ...    100.07  Snow Showers
45      1/2/2012 21:00         -5.8  ...    100.15  Snow Showers
47      1/2/2012 23:00         -7.4  ...    100.27  Snow Showers
48       1/3/2012 0:00         -9.0  ...    100.35  Snow Showers
...                ...          ...  ...       ...           ...
8779  12/31/2012 19:00          0.1  ...    100.13          Snow
8780  12/31/2012 20:00          0.2  ...    100.03          Snow
8781  12/31/2012 21:00         -0.5  ...     99.95          Snow
8782  12/31/2012 22:00         -0.2  ...     99.91          Snow
8783  12/31/2012 23:00          0.0  ...     99.89          Snow

[583 rows x 8 columns]

Finding instances when windspeed is above 24 and visibility 25

In [ ]:
data.head(2)

       Date_Time  Temperature  Dew_Pt_Temp  ...  Visibility  Pressure  Weather
0  1/1/2012 0:00         -1.8         -3.9  ...         8.0    101.24      Fog
1  1/1/2012 1:00         -1.8         -3.7  ...         8.0    101.24      Fog

[2 rows x 8 columns]

In [ ]:
data[(data['Wind_Speed']>24) & (data['Visibility']==25)]

             Date_Time  Temperature  ...  Pressure        Weather
23      1/1/2012 23:00          5.3  ...     99.31         Cloudy
24       1/2/2012 0:00          5.2  ...     99.26   Rain Showers
25       1/2/2012 1:00          4.6  ...     99.26         Cloudy
26       1/2/2012 2:00          3.9  ...     99.26  Mostly Cloudy
27       1/2/2012 3:00          3.7  ...     99.30  Mostly Cloudy
...                ...          ...  ...       ...            ...
8705  12/28/2012 17:00         -8.6  ...    101.34   Mainly Clear
8753  12/30/2012 17:00        -12.1  ...    101.26   Mainly Clear
8755  12/30/2012 19:00        -13.4  ...    101.47   Mainly Clear
8759  12/30/2012 23:00        -12.1  ...    101.52  Mostly Cloudy
8760   12/31/2012 0:00        -11.1  ...    101.51         Cloudy

[308 rows x 8 columns]

Finding the mean value of all weather condition against each columns.

In [ ]:
data.groupby('Weather').mean()

                                         Temperature  ...    Pressure
Weather                                               ...
Clear                                       6.825716  ...  101.587443
Cloudy                                      7.970544  ...  100.911441
Drizzle                                     7.353659  ...  100.435366
Drizzle,Fog                                 8.067500  ...  100.786625
Drizzle,Ice Pellets,Fog                     0.400000  ...  100.790000
Drizzle,Snow                                1.050000  ...  100.890000
Drizzle,Snow,Fog                            0.693333  ...   99.281333
Fog                                         4.303333  ...  101.184067
Freezing Drizzle                           -5.657143  ...  100.202857
Freezing Drizzle,Fog                       -2.533333  ...  100.441667
Freezing Drizzle,Haze                      -5.433333  ...  100.316667
Freezing Drizzle,Snow                      -5.109091  ...  100.520909
Freezing Fog                               -7.575000  ...  102.320000
Freezing Rain                              -3.885714  ...   99.647143
Freezing Rain,Fog                          -2.225000  ...   99.945000
Freezing Rain,Haze                         -4.900000  ...  100.375000
Freezing Rain,Ice Pellets,Fog              -2.600000  ...  100.950000
Freezing Rain,Snow Grains                  -5.000000  ...   98.560000
Haze                                       -0.200000  ...  101.482500
Mainly Clear                               12.558927  ...  101.248832
Moderate Rain,Fog                           1.700000  ...   99.980000
Moderate Snow                              -5.525000  ...  100.275000
Moderate Snow,Blowing Snow                 -5.450000  ...  100.570000
Mostly Cloudy                              10.574287  ...  101.025288
Rain                                        9.786275  ...  100.233333
Rain Showers                               13.722340  ...  100.404043
Rain Showers,Fog                           12.800000  ...   99.830000
Rain Showers,Snow Showers                   2.150000  ...  101.100000
Rain,Fog                                    8.273276  ...  100.500862
Rain,Haze                                   4.633333  ...  100.540000
Rain,Ice Pellets                            0.600000  ...  100.120000
Rain,Snow                                   1.055556  ...   99.951111
Rain,Snow Grains                            1.900000  ...  100.600000
Rain,Snow,Fog                               0.800000  ...  100.730000
Rain,Snow,Ice Pellets                       1.100000  ...  100.105000
Snow                                       -4.524103  ...  100.536103
Snow Pellets                                0.700000  ...   99.700000
Snow Showers                               -3.506667  ...  100.963500
Snow Showers,Fog                          -10.675000  ...  101.292500
Snow,Blowing Snow                          -5.410526  ...   99.704737
Snow,Fog                                   -5.075676  ...  100.688649
Snow,Haze                                  -4.020000  ...  100.782000
Snow,Ice Pellets                           -1.883333  ...  100.548333
Thunderstorms                              24.150000  ...  100.230000
Thunderstorms,Heavy Rain Showers           10.900000  ...  100.260000
Thunderstorms,Moderate Rain Showers,Fog    19.600000  ...  100.010000
Thunderstorms,Rain                         20.433333  ...  100.420000
Thunderstorms,Rain Showers                 20.037500  ...  100.233750
Thunderstorms,Rain Showers,Fog             21.600000  ...  100.063333
Thunderstorms,Rain,Fog                     20.600000  ...  100.080000

[50 rows x 6 columns]

Finding the minimum value of each column against the weather condition.

In [ ]:
data.groupby('Weather').min()

                                                Date_Time  ...  Pressure
Weather                                                    ...
Clear                                      1/11/2012 1:00  ...     99.52
Cloudy                                     1/1/2012 17:00  ...     98.39
Drizzle                                   1/23/2012 21:00  ...     97.84
Drizzle,Fog                               1/23/2012 20:00  ...     98.65
Drizzle,Ice Pellets,Fog                   12/17/2012 9:00  ...    100.79
Drizzle,Snow                             12/17/2012 15:00  ...    100.63
Drizzle,Snow,Fog                         12/18/2012 21:00  ...     97.79
Fog                                         1/1/2012 0:00  ...     98.31
Freezing Drizzle                          1/13/2012 10:00  ...     98.44
Freezing Drizzle,Fog                        1/1/2012 2:00  ...     98.74
Freezing Drizzle,Haze                      2/1/2012 11:00  ...    100.28
Freezing Drizzle,Snow                      1/13/2012 3:00  ...     99.19
Freezing Fog                               1/22/2012 6:00  ...    101.97
Freezing Rain                             1/13/2012 11:00  ...     98.22
Freezing Rain,Fog                         1/17/2012 23:00  ...     98.32
Freezing Rain,Haze                         2/1/2012 14:00  ...    100.34
Freezing Rain,Ice Pellets,Fog             12/17/2012 3:00  ...    100.95
Freezing Rain,Snow Grains                  1/13/2012 9:00  ...     98.56
Haze                                      1/22/2012 12:00  ...    100.35
Mainly Clear                              1/10/2012 11:00  ...     98.67
Moderate Rain,Fog                         12/10/2012 8:00  ...     99.98
Moderate Snow                             1/12/2012 15:00  ...     99.88
Moderate Snow,Blowing Snow               12/27/2012 10:00  ...    100.50
Mostly Cloudy                              1/1/2012 16:00  ...     98.36
Rain                                       1/1/2012 18:00  ...     97.52
Rain Showers                               1/1/2012 22:00  ...     98.51
Rain Showers,Fog                          10/20/2012 3:00  ...     99.83
Rain Showers,Snow Showers                  11/4/2012 8:00  ...    101.09
Rain,Fog                                  1/23/2012 18:00  ...     98.61
Rain,Haze                                  3/13/2012 7:00  ...    100.50
Rain,Ice Pellets                          12/18/2012 5:00  ...    100.12
Rain,Snow                                  1/10/2012 5:00  ...     98.18
Rain,Snow Grains                          12/21/2012 0:00  ...    100.60
Rain,Snow,Fog                             12/8/2012 21:00  ...    100.73
Rain,Snow,Ice Pellets                     12/21/2012 1:00  ...     99.85
Snow                                       1/10/2012 1:00  ...     97.75
Snow Pellets                             11/24/2012 15:00  ...     99.70
Snow Showers                               1/12/2012 7:00  ...     99.49
Snow Showers,Fog                          12/26/2012 9:00  ...    100.63
Snow,Blowing Snow                         1/13/2012 21:00  ...     98.11
Snow,Fog                                 12/16/2012 15:00  ...     99.38
Snow,Haze                                  2/1/2012 17:00  ...    100.61
Snow,Ice Pellets                          12/10/2012 3:00  ...     99.40
Thunderstorms                              7/16/2012 1:00  ...     99.84
Thunderstorms,Heavy Rain Showers           5/29/2012 6:00  ...    100.26
Thunderstorms,Moderate Rain Showers,Fog    7/17/2012 6:00  ...    100.01
Thunderstorms,Rain                        5/25/2012 20:00  ...    100.19
Thunderstorms,Rain Showers                5/29/2012 16:00  ...     99.65
Thunderstorms,Rain Showers,Fog             6/29/2012 3:00  ...     99.71
Thunderstorms,Rain,Fog                     7/17/2012 5:00  ...    100.08

[50 rows x 7 columns]

Finding the miaximum value of each column against the weather condition.

In [ ]:
data.groupby('Weather').max()

                                                Date_Time  ...  Pressure
Weather                                                    ...
Clear                                       9/9/2012 5:00  ...    103.63
Cloudy                                     9/9/2012 23:00  ...    103.65
Drizzle                                    9/30/2012 3:00  ...    101.56
Drizzle,Fog                                9/30/2012 2:00  ...    102.07
Drizzle,Ice Pellets,Fog                   12/17/2012 9:00  ...    100.79
Drizzle,Snow                             12/19/2012 18:00  ...    101.15
Drizzle,Snow,Fog                          12/22/2012 3:00  ...    100.15
Fog                                        9/22/2012 0:00  ...    103.04
Freezing Drizzle                            2/1/2012 5:00  ...    101.02
Freezing Drizzle,Fog                      12/10/2012 5:00  ...    101.27
Freezing Drizzle,Haze                      2/1/2012 13:00  ...    100.36
Freezing Drizzle,Snow                      3/2/2012 12:00  ...    101.18
Freezing Fog                               3/17/2012 6:00  ...    102.85
Freezing Rain                               2/1/2012 7:00  ...    101.00
Freezing Rain,Fog                         12/17/2012 1:00  ...    101.01
Freezing Rain,Haze                         2/1/2012 15:00  ...    100.41
Freezing Rain,Ice Pellets,Fog             12/17/2012 3:00  ...    100.95
Freezing Rain,Snow Grains                  1/13/2012 9:00  ...     98.56
Haze                                      3/13/2012 23:00  ...    102.97
Mainly Clear                                9/9/2012 9:00  ...    103.59
Moderate Rain,Fog                         12/10/2012 8:00  ...     99.98
Moderate Snow                             12/27/2012 9:00  ...    100.67
Moderate Snow,Blowing Snow               12/27/2012 12:00  ...    100.64
Mostly Cloudy                               9/9/2012 2:00  ...    103.65
Rain                                        9/5/2012 2:00  ...    102.26
Rain Showers                               9/8/2012 16:00  ...    102.31
Rain Showers,Fog                          10/20/2012 3:00  ...     99.83
Rain Showers,Snow Showers                 12/5/2012 10:00  ...    101.11
Rain,Fog                                  9/30/2012 23:00  ...    101.77
Rain,Haze                                  3/13/2012 9:00  ...    100.61
Rain,Ice Pellets                          12/18/2012 5:00  ...    100.12
Rain,Snow                                  4/23/2012 3:00  ...    101.07
Rain,Snow Grains                          12/21/2012 0:00  ...    100.60
Rain,Snow,Fog                             12/8/2012 21:00  ...    100.73
Rain,Snow,Ice Pellets                     12/21/2012 5:00  ...    100.47
Snow                                       4/27/2012 9:00  ...    102.73
Snow Pellets                             11/24/2012 15:00  ...     99.70
Snow Showers                               3/4/2012 21:00  ...    102.50
Snow Showers,Fog                         12/29/2012 13:00  ...    102.52
Snow,Blowing Snow                          2/25/2012 9:00  ...    100.62
Snow,Fog                                  3/14/2012 19:00  ...    102.07
Snow,Haze                                  2/1/2012 21:00  ...    100.99
Snow,Ice Pellets                            3/3/2012 4:00  ...    100.96
Thunderstorms                              7/4/2012 16:00  ...    100.62
Thunderstorms,Heavy Rain Showers           5/29/2012 6:00  ...    100.26
Thunderstorms,Moderate Rain Showers,Fog    7/17/2012 6:00  ...    100.01
Thunderstorms,Rain                        7/23/2012 18:00  ...    100.83
Thunderstorms,Rain Showers                  9/8/2012 4:00  ...    101.06
Thunderstorms,Rain Showers,Fog            7/31/2012 20:00  ...    100.64
Thunderstorms,Rain,Fog                     7/17/2012 5:00  ...    100.08

[50 rows x 7 columns]

Finding all the instances where weather is Fog

In [ ]:
# VAlue Counts
data.Weather.value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Snow Showers,Fog                              4
Freezing Fog                                  4
Moderate Snow                                 4
Freezing Rain,Fog                             4
Rain,Snow,Ice Pellets                         4
Rain,Haze                                     3
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Rain Showers,Snow Showers                     2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Thunderstorms,Moderate Rain Showers,Fog       1
Freezing Rain,Snow Grains                     1
Rain,Ice Pellets                              1
Drizzle,Ice Pellets,Fog                       1
Rain Showers,Fog                              1
Rain,Snow Grains                              1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Rain,Snow,Fog                                 1
Thunderstorms,Rain,Fog                        1
Snow Pellets                                  1
Thunderstorms,Heavy Rain Showers              1
Name: Weather, dtype: int64

In [ ]:
# Filtering
data[data.Weather=='Fog']

             Date_Time  Temperature  Dew_Pt_Temp  ...  Visibility  Pressure  Weather
0        1/1/2012 0:00         -1.8         -3.9  ...         8.0    101.24      Fog
1        1/1/2012 1:00         -1.8         -3.7  ...         8.0    101.24      Fog
4        1/1/2012 4:00         -1.5         -3.3  ...         4.8    101.23      Fog
5        1/1/2012 5:00         -1.4         -3.3  ...         6.4    101.27      Fog
6        1/1/2012 6:00         -1.5         -3.1  ...         6.4    101.29      Fog
...                ...          ...          ...  ...         ...       ...      ...
8716   12/29/2012 4:00        -16.0        -17.2  ...         9.7    101.25      Fog
8717   12/29/2012 5:00        -14.8        -15.9  ...         6.4    101.25      Fog
8718   12/29/2012 6:00        -13.8        -15.3  ...         9.7    101.25      Fog
8719   12/29/2012 7:00        -14.8        -16.4  ...         8.0    101.22      Fog
8722  12/29/2012 10:00        -12.0        -13.3  ...         6.4    101.15      Fog

[150 rows x 8 columns]

In [ ]:
# Groupby
data.groupby('Weather').get_group('Fog')

             Date_Time  Temperature  Dew_Pt_Temp  ...  Visibility  Pressure  Weather
0        1/1/2012 0:00         -1.8         -3.9  ...         8.0    101.24      Fog
1        1/1/2012 1:00         -1.8         -3.7  ...         8.0    101.24      Fog
4        1/1/2012 4:00         -1.5         -3.3  ...         4.8    101.23      Fog
5        1/1/2012 5:00         -1.4         -3.3  ...         6.4    101.27      Fog
6        1/1/2012 6:00         -1.5         -3.1  ...         6.4    101.29      Fog
...                ...          ...          ...  ...         ...       ...      ...
8716   12/29/2012 4:00        -16.0        -17.2  ...         9.7    101.25      Fog
8717   12/29/2012 5:00        -14.8        -15.9  ...         6.4    101.25      Fog
8718   12/29/2012 6:00        -13.8        -15.3  ...         9.7    101.25      Fog
8719   12/29/2012 7:00        -14.8        -16.4  ...         8.0    101.22      Fog
8722  12/29/2012 10:00        -12.0        -13.3  ...         6.4    101.15      Fog

[150 rows x 8 columns]

In [ ]:
#Str.contains
data[data.Weather.str.contains('Fog')]

             Date_Time  Temperature  ...  Pressure               Weather
0        1/1/2012 0:00         -1.8  ...    101.24                   Fog
1        1/1/2012 1:00         -1.8  ...    101.24                   Fog
2        1/1/2012 2:00         -1.8  ...    101.26  Freezing Drizzle,Fog
3        1/1/2012 3:00         -1.5  ...    101.27  Freezing Drizzle,Fog
4        1/1/2012 4:00         -1.5  ...    101.23                   Fog
...                ...          ...  ...       ...                   ...
8739   12/30/2012 3:00         -9.1  ...    100.30              Snow,Fog
8740   12/30/2012 4:00         -9.3  ...    100.28              Snow,Fog
8741   12/30/2012 5:00         -9.1  ...    100.32              Snow,Fog
8742   12/30/2012 6:00         -9.3  ...    100.39              Snow,Fog
8770  12/31/2012 10:00         -7.4  ...    101.05              Snow,Fog

[426 rows x 8 columns]

Finding instances where weather is clear and visibility is above 40.

In [ ]:
data[(data.Weather=='Clear') & (data.Visibility>40)]

             Date_Time  Temperature  Dew_Pt_Temp  ...  Visibility  Pressure  Weather
351    1/15/2012 15:00        -15.4        -22.8  ...        48.3    102.71    Clear
352    1/15/2012 16:00        -15.1        -22.8  ...        48.3    102.79    Clear
425    1/18/2012 17:00        -11.3        -18.8  ...        48.3    101.54    Clear
440     1/19/2012 8:00        -13.7        -18.4  ...        48.3    101.84    Clear
441     1/19/2012 9:00        -12.7        -17.2  ...        48.3    101.73    Clear
...                ...          ...          ...  ...         ...       ...      ...
8384   12/15/2012 8:00        -10.7        -15.6  ...        48.3    102.69    Clear
8385   12/15/2012 9:00        -10.4        -15.9  ...        48.3    102.74    Clear
8389  12/15/2012 13:00         -8.4        -14.7  ...        48.3    102.64    Clear
8631  12/25/2012 15:00         -7.1        -13.7  ...        48.3    101.98    Clear
8632  12/25/2012 16:00         -7.5        -13.9  ...        48.3    102.03    Clear

[313 rows x 8 columns]

Finding all instances when
>> (a) Weather is clear and Relative_Humidity is greater than 50.
>> (b)or Visibility > 50

In [ ]:
data[((data.Weather=='Clear') & (data.Relative_Humidity>50)) | (data.Visibility>40)]

             Date_Time  Temperature  ...  Pressure        Weather
106     1/5/2012 10:00         -6.0  ...    100.45   Mainly Clear
107     1/5/2012 11:00         -5.6  ...    100.41   Mainly Clear
108     1/5/2012 12:00         -4.7  ...    100.38   Mainly Clear
109     1/5/2012 13:00         -4.4  ...    100.40   Mainly Clear
110     1/5/2012 14:00         -5.1  ...    100.46   Mainly Clear
...                ...          ...  ...       ...            ...
8749  12/30/2012 13:00        -12.4  ...    100.92  Mostly Cloudy
8750  12/30/2012 14:00        -11.8  ...    100.96   Mainly Clear
8751  12/30/2012 15:00        -11.3  ...    101.05   Mainly Clear
8752  12/30/2012 16:00        -11.4  ...    101.15   Mainly Clear
8756  12/30/2012 20:00        -13.8  ...    101.52          Clear

[2921 rows x 8 columns]